---
title: "Figuring things out"
author: "Reane Loiselle"
date: "`r format(Sys.time(), '%A, %d-%b-%y')`"
output:
  html_document:
    theme: yeti
    highlight: pygments
  pdf_document: default
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, results="hide"}
## Generally you will not edit this chunk at all.
knitr::opts_chunk$set(echo=TRUE,fig.width=14,fig.height=5,comment="#R>")
library(tidyverse)
library(lubridate)
library(magrittr)
```

<!---- set working directory ---->
```{r,echo=FALSE}
d <- read_csv("LLO_Burke_TROLL_21.csv") %>%
  mutate(Date=as.Date(Date,format="%m/%d/%y"))
```

##Chunk on Specific Conductance
```{r, results='hide'}
sp <- d %>%
  select(Site,Date,m,SpCond) %>%
  filter(m<=2) %>%
  na.omit(sp)
sp_sum <- sp %>%
  group_by(Site,Date) %>%
  summarize(n=n(),
            mn_SpCond=mean(SpCond,na.rm=TRUE),
            sd_spCond=sd(SpCond,na.rm=TRUE)) %>%
  ungroup() %>%
  arrange(factor(Site, levels = c('WE1a', 'WE1b', 'AR2a', 'AR2b', 'BR3a', 'BR3b', 'BR3c',"FR4a","FR4b","FR4c","Bbay","LLO4","SBay","MB5a","MB5c","SCav","6a","6b","7a","7b","8a","8b","9a","CB10","CB11","10a","CB1","CB3","11a","11b","11c")))
sp_sum

sp2 <- d %>%
  select(Site,Date,m,SpCond) %>%
  na.omit(sp2)
sp2_sum <- sp2 %>%
  group_by(Site,Date) %>%
  summarize(n=n(),
            mn_SpCond=mean(SpCond,na.rm=TRUE),
            sd_spCond=sd(SpCond,na.rm=TRUE)) %>%
  ungroup() %>%
   arrange(factor(Site, levels = c('WE1a', 'WE1b', 'AR2a', 'AR2b', 'BR3a', 'BR3b', 'BR3c',"FR4a","FR4b","FR4c","Bbay","LLO4","SBay","MB5a","MB5c","SCav","6a","6b","7a","7b","8a","8b","9a","CB10","CB11","10a","CB1","CB3","11a","11b","11c")))
sp2_sum

```
##Graphs on Specific Conductance
##0-2m Profiles
```{r}
ggplot(sp_sum, aes(x = reorder(Site, -mn_SpCond),y= mn_SpCond,color = Site)) +
  geom_boxplot(data = sp_sum, aes(y = mn_SpCond), size = 2) +
  labs(x="Sites",y="0-2m Mean Specific Conductance") +
  theme(legend.position = "none") 

ggplot(sp_sum, aes(x = factor(Site,level = c('WE1a', 'WE1b', 'AR2a', 'AR2b', 'BR3a', 'BR3b', 'BR3c',"FR4a","FR4b","FR4c","Bbay","LLO4","SBay","MB5a","MB5c","SCav","6a","6b","7a","7b","8a","8b","9a","CB10","CB11","10a","CB1","CB3","11a","11b","11c")),y= mn_SpCond,color = Site)) +
  geom_boxplot(data = sp_sum, aes(y = mn_SpCond), size = 2) +
  labs(x="Sites",y="0-2m Mean Specific Conductance") +
  theme(legend.position = "none")
```

```{r, echo=FALSE}
ggplot(sp_sum, aes(x = reorder(Site, -mn_SpCond),y= mn_SpCond,color = Site)) +
  geom_jitter(data = sp_sum, aes(y = mn_SpCond), size = 2) +
  labs(x="Sites",y="0-2m Mean Specific Conductance") +
  theme(legend.position = "none")

ggplot(sp_sum, aes(x = factor(Site,level = c('WE1a', 'WE1b', 'AR2a', 'AR2b', 'BR3a', 'BR3b', 'BR3c',"FR4a","FR4b","FR4c","Bbay","LLO4","SBay","MB5a","MB5c","SCav","6a","6b","7a","7b","8a","8b","9a","CB10","CB11","10a","CB1","CB3","11a","11b","11c")),y= mn_SpCond,color = Site)) +
  geom_jitter(data = sp_sum, aes(y = mn_SpCond), size = 2) +
  labs(x="Sites",y="0-2m Mean Specific Conductance") +
  theme(legend.position = "none")
```
##Full Profiles
```{r, echo=FALSE}
ggplot(sp2_sum, aes(x = reorder(Site, -mn_SpCond),y= mn_SpCond,color = Site)) +
  geom_jitter(data = sp2_sum, aes(y = mn_SpCond), size = 2) +
  labs(x="Sites",y="Mean Specific Conductance") +
  theme(legend.position = "none")

ggplot(sp2_sum, aes(x = factor(Site,level = c('WE1a', 'WE1b', 'AR2a', 'AR2b', 'BR3a', 'BR3b', 'BR3c',"FR4a","FR4b","FR4c","Bbay","LLO4","SBay","MB5a","MB5c","SCav","6a","6b","7a","7b","8a","8b","9a","CB10","CB11","10a","CB1","CB3","11a","11b","11c")),y= mn_SpCond,color = Site)) +
  geom_jitter(data = sp2_sum, aes(y = mn_SpCond), size = 2) +
  labs(x="Sites",y="Mean Specific Conductance") +
  theme(legend.position = "none")
```
